apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pentest
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["bin/bash", "-c", "sleep 10000"]
    securityContext:
      readOnlyRootFilesystem: true
