global:
  domain: lab-keycloak.test
  namespace: web-app

networkPolicy:
  port: 53

roleBinding:
  subjects:
    kind: ServiceAccount
    name: default

keycloak:
  appName: keycloak
  replicaCount: 1
  image:
    repository: quay.io/keycloak/keycloak
    tag: latest
  port: 8080
