apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: canary-vpa
  namespace: web-app
spec:
  targetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: canary-demo
  updatePolicy:
    updateMode: "Off"
