[k3s_servers]
Node-1 ansible_host=172.28.64.1 ansible_port=2222 ansible_user=favom ansible_ssh_private_key_file=~/.ssh/id_rsa internal_ip=192.168.100.3

[k3s_agents]
Node-2 ansible_host=172.28.64.1 ansible_port=2223 ansible_user=favom ansible_ssh_private_key_file=~/.ssh/id_rsa internal_ip=192.168.100.4
Node-3 ansible_host=172.28.64.1 ansible_port=2224 ansible_user=favom ansible_ssh_private_key_file=~/.ssh/id_rsa internal_ip=192.168.100.5

[k3s_cluster:children]
k3s_servers
k3s_agents
