apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }} 
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.keycloak.replicaCount }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "keycloak.name" . }}
        image: {{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}
        ports:
        - containerPort: {{ .Values.keycloak.port }}
        args:
    		- start
    		- --http-enabled=true
    		- --hostname-strict=false
    		- --verbose
        env:
          {{- range .Values.keycloak.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
          {{- end }}

