kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: sso-system
  namespace: fleet-local
spec:
  repo: https://github.com/NurkhanZ/DevOps2.git
  branch: main
  paths:
    - endterm_dir/infrastructure/networking
    - endterm_dir/infrastructure/security
    - endterm_dir/infrastructure/logging
    - endterm_dir/infrastructure/observability
    - endterm_dir/apps/postgres
    - endterm_dir/apps/keycloak
  targets:
    - clusterName: local
      namespace: sso-system
      createNamespace: true
