kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: sso-stack
  namespace: fleet-default
spec:
  # Replace with your actual git repository URL
  repo: https://github.com/NurkhanZ/DevOps2.git
  branch: main
  paths:
    - endterm_dir/config
    - endterm_dir/postgres
    - endterm_dir/keycloak
  targets:
    - clusterName: local
