apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "postgres.fullname" . }}-service-headless
  replicas: {{ .Values.postgres.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "postgres.selectorLabels" . | nindent 8}}
    spec:
      containers:
      - name: {{ include "postgres.name" . }}
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        ports:
        - containerPort: {{ .Values.postgres.port }}
        env:
          {{- range .Values.postgres.env }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
        volumeMounts:
        - name: {{ .Values.postgres.volumeMounts.name }}
          mountPath: {{ .Values.postgres.volumeMounts.mountPath }}
        livenessProbe:
          exec:
            command:
            - /usr/bin/pg_isready
            - "-U"
            - "keycloak"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /usr/bin/pg_isready
            - "-U"
            - "keycloak"
            - "-d"
            - "keycloakdb"
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.postgres.volumeMounts.name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.postgres.resources.storage }}
