apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  default-setting.yaml: |-
    backup-target: ""
    default-replica-count: 3
    storage-over-provisioning-percentage: 100
    storage-minimal-available-percentage: 10
    concurrent-replica-rebuild-per-node-limit: 1
    v2-data-engine: false
    guaranteed-engine-manager-cpu: 5
    guaranteed-replica-manager-cpu: 5
