{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-backup-s3
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: {{ .Values.sealedSecrets.longhornS3.AWS_ACCESS_KEY_ID | quote }}
    AWS_SECRET_ACCESS_KEY: {{ .Values.sealedSecrets.longhornS3.AWS_SECRET_ACCESS_KEY | quote }}
    AWS_ENDPOINTS: {{ .Values.sealedSecrets.longhornS3.AWS_ENDPOINTS | quote }}
  template:
    metadata:
      name: longhorn-backup-s3
    type: Opaque
{{- end }}
