apiVersion: v1
kind: ResourceQuota
metadata:
  name: sso-resource-quota
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    requests.cpu: "4"
    limits.cpu: "6"
    requests.memory: "3Gi"
    limits.memory: "4.5Gi"
    pods: "20"
    persistentvolumeclaims: "10"

