apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-role-deploy
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbac-operator
  template:
    metadata:
      labels:
        app: rbac-operator
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: webhook
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        image: python:3.9-slim
        command: ["python", "/hooks/sync.py"]
        volumeMounts:
        - name: code
          mountPath: /hooks
        ports:
        - containerPort: 8080
      volumes:
      - name: code
        configMap:
          name: webhook-cm-role
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-role-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: rbac-operator
  ports:
  - port: 80
    targetPort: 8080
