{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sso-credentials
  namespace: {{ .Values.global.namespace }}
spec:
  encryptedData:
    POSTGRES_USER: {{ .Values.sealedSecrets.ssoCredentials.POSTGRES_USER | quote }}
    POSTGRES_PASSWORD: {{ .Values.sealedSecrets.ssoCredentials.POSTGRES_PASSWORD | quote }}
    KEYCLOAK_ADMIN: {{ .Values.sealedSecrets.ssoCredentials.KEYCLOAK_ADMIN | quote }}
    KEYCLOAK_ADMIN_PASSWORD: {{ .Values.sealedSecrets.ssoCredentials.KEYCLOAK_ADMIN_PASSWORD | quote }}
  template:
    metadata:
      name: sso-credentials
    type: Opaque
{{- end }}
