apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: sso-metrics-db
  namespace: {{ .Values.global.namespace }}
spec:
  retentionPeriod: "14"
  replicaCount: 1
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "local-path"
        resources:
          requests:
            storage: 5Gi
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "150Mi"
