apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-keycloak-forward-headers
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-keycloak-ingress
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  tls:
    secretName: sso-tls-secret
  routes:
    - match: Host(`{{ .Values.global.domain }}`)
      kind: Rule
      services:
        - name: traefik-canary-splitter
          port: 8080
          kind: TraefikService
      middlewares:
        - name: traefik-keycloak-forward-headers
