apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-memory
  namespace: best-effort-ns
spec:
  hard:
    requests.memory: 1Gi
    limits.memory: 1Gi
    pods: "10"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: protected-pod
value: 100000
preemptionPolicy: Never
globalDefault: false
