apiVersion: v1
kind: Pod
metadata:
  name: burstable-3
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: simulate
            operator: In
            values:
            - eviction
  containers:
  - name: burst
    image: polinux/stress
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "350M", "--vm-hang", "0"]
    resources:
      requests:
        memory: "100Mi"
