keycloak:
  appName: keycloak
  replicaCount: 2
  image:
    repository: quay.io/keycloak/keycloak
    tag: 26.6.0
  port: 8080
  canary:
    enabled: false
    replicaCount: 1
    image:
      repository: quay.io/keycloak/keycloak
      tag: 26.6.1
