global:
  domain: sso-system.test
  namespace: sso-system

keycloak:
  appName: keycloak
  replicaCount: 1
  image:
    repository: quay.io/keycloak/keycloak
    tag: 26.6.1
  port: 8080
  canary:
    enabled: false
    replicaCount: 1
    image:
      repository: quay.io/keycloak/keycloak
      tag: 26.6.1
