global:
  domain: sso-system.test
  namespace: sso-system

#TODO roleBinding

keycloak:
  appName: keycloak
  replicaCount: 1
  image:
    repository: quay.io/keycloak/keycloak
    tag: 26.6.1
  port: 8080
