apiVersion: v1
kind: Service
metadata:
  name: postgres-service-headless
  namespace: {{ .Values.global.namespace }}
  labels:
    app: postgres
spec:
  ports:
  - name: {{ .Values.postgres.appName }}
    port: {{ .Values.postgres.port }}
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: postgres
spec:
  ports:
  - name: {{ .Values.postgres.appName }}
    port: {{ .Values.postgres.port }}
  selector:
    app: postgres
