apiVersion: apps/v1
kind: Statefulset
metadata:
  name : {{ include "postgres.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "postgres.fullname" . }}-service-headless
  replicas: {{ .Values.postgres.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "postgres.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "postgres.name" . }}
        image: "{{ .Values.postgres.image.repository }}: {{ .Values.postgres.image.tag }}"
        ports:
        - containerPort: {{ .Values.postgres.port }}
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: sso-service-credentials
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: sso-service-credentials
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sso-service-credentials
                key: POSTGRES_PASSWORD
        volumeMounts:
        - name: {{ .Values.postgres.volumeMounts.name }}
          mountPath: {{ .Values.postgres.volumeMounts.mountPath }}
        livenessProbe:
          exec:
            command:
            - /usr/bin/pg_isready
            - "-U"
            - "sso_u"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /usr/bin/pg_isready
            - "-U"
            - "sso_u"
            - "-d"
            - "sso_db"
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.postgres.volumeMounts.name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.postgres.resources.storage }}

