apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.keycloak.appName }}
spec:
  replicas: {{ .Values.keycloak.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.keycloak.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.keycloak.appName }}
    spec:
      containers:
      - name: {{ .Values.keycloak.appName }}
        image: {{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}
        ports:
        - containerPort: {{ .Values.keycloak.port }}
        args: ["start", "--http-enabled=true", "--hostname-strict=false"]
        env:
          {{- range .Values.keycloak.env }}
        - name: {{ .name }}
          value: {{ .value }}
          {{- end }}

