apiVersion: v1
kind: Service
metadata:
  name: postgres-headless-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.postgres.appName }}
spec:
  ports:
  - name: {{ .Values.postgres.appName }}
    port: {{ .Values.postgres.port }}
  clusterIP: None
  selector:
    app: {{ .Values.postgres.appName }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.postgres.appName }}
spec:
  ports:
  - name: {{ .Values.postgres.appName }}
    port: {{ .Values.postgres.port }}
  selector:
    app: {{ .Values.postgres.appName }}
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.keycloak.appName }}
  ports:
  - port: {{ .Values.keycloak.port }}
    targetPort: {{ .Values.keycloak.port }}
