apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: sso-metrics-db
  namespace: {{ .Release.Namespace }}
spec:
  retentionPeriod: "14"
  replicaCount: 1
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "local-path"
        resources:
          requests:
            storage: 5Gi
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "150Mi"
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: sso-metrics-agent
  namespace: {{ .Release.Namespace }}
spec:
  selectAllByDefault: true
  remoteWrite:
    - url: http://vmsingle-sso-metrics-db.sso-system.svc.cluster.local:8429/api/v1/write
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: keycloak-pod-scrape
  namespace: {{ .Release.Namespace }}
spec:
  podMetricsEndpoints:
  - port: management
    path: /metrics
    interval: 15s
  selector:
    matchLabels:
      app: keycloak

