apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc-stable
  namespace: {{ .Values.global.namespace }}
  labels:
    app: keycloak-stable
spec:
  selector:
    app: keycloak-stable
  ports:
  - port: {{ .Values.keycloak.port }}
    targetPort: {{ .Values.keycloak.port }}
{{- if .Values.keycloak.canary.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc-canary
  namespace: {{ .Values.global.namespace }}
  labels:
    app: keycloak-canary
spec:
  selector:
    app: keycloak-canary
  ports:
  - port: {{ .Values.keycloak.port }}
    targetPort: {{ .Values.keycloak.port }}
{{- end }}
