- hosts: localhost
  connection: local
  become: yes

  vars:
    user: favom

  tasks:
  - name: Update pacman
    pacman: 
      update_cache: yes
      upgrade: yes

  - name: Install base dependencies
    pacman:
      name:
        - curl
        - wget
        - virtualbox
        - virtualbox-host-modules-arch
        - kubectl
        - conntrack-tools
        - socat
        - minikube
      state: present

  - name: Add user to vboxusers group
    user: 
      name: "{{ user }}"
      groups: vboxusers
      append: yes

  - name: Start minikube cluster
    shell: |
      minikube start --driver=virtualbox --nodes=3 --force
    environment:
      CHANGE_MINIKUBE_NONE_USER: "true"

  - name: Wait for nodes to be ready
    command: kubectl wait --for=condition=Ready nodes --all --timeout=120s

  - name: Copy kubeconfig for runner user
    copy:
      src: /root/.kube/config
      dest: /var/lib/gitlab-runner/.kube/config
      remote_src: yes
      owner: gitlab-runner
      group: gitlab-runner
      mode: '0600'

