{{- if not .Values.sealedSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-s3-backup-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "YOUR_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "YOUR_SECRET_KEY"
  S3_BUCKET: "s3://your-bucket-name"
  S3_REGION: "us-east-1"
  S3_ENDPOINT: "https://s3.amazonaws.com" # Change if using MinIO or Spaces
{{- end }}

