apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "0 2 * * *" # Every day at 2 AM
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: postgres-backup
        spec:
          containers:
          - name: postgres-backup
            image: postgres:15-alpine
            command:
            - /bin/sh
            - -c
            - |
              export PGPASSWORD=$POSTGRES_PASSWORD
              BACKUP_FILE="/backup/keycloak_$(date +%F).sql"
              pg_dump -h postgres-service-headless -U $POSTGRES_USER keycloak > $BACKUP_FILE
              
              echo "Installing AWS CLI..."
              apk add --no-cache aws-cli
              
              echo "Uploading backup to S3..."
              aws --endpoint-url=$S3_ENDPOINT s3 cp $BACKUP_FILE $S3_BUCKET/keycloak_$(date +%F).sql
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sso-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sso-credentials
                  key: POSTGRES_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: postgres-s3-backup-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres-s3-backup-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: postgres-s3-backup-credentials
                  key: S3_BUCKET
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: postgres-s3-backup-credentials
                  key: S3_REGION
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: postgres-s3-backup-credentials
                  key: S3_ENDPOINT
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: postgres-snapshots-pvc

