global:
  domain: lab-keycloak.test
  namespace: web-app

networkPolicy:
  port: 53

roleBinding:
  subjects:
    kind: ServiceAccount
    name: default

postgres:
  appName: postgres
  replicaCount: 1
  image:
    repository: postgres
    tag: 15
  port: 5432
  volumeMounts:
    name: pgdata
    mountPath: /var/lib/postgresql/data
  resources:
    storage: 1Gi


